name: ui_kit
description: A Flutter UI/UX pack.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  floating_bottom_navigation_bar: ^1.4.1
  animations: ^1.1.2
  get: ^3.13.2
  supercharged: ^1.10.0
  lottie: ^0.6.0
  easy_localization: ^2.3.3
  smooth_page_indicator: ^0.2.0
  introduction_screen: ^1.0.9
  flutter_linkify: ^3.1.3
  flutter_neumorphic: ^3.0.3
  carousel_slider: ^2.3.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
      - family: Montserrat
        fonts:
           - asset: fonts/Montserrat-Regular.ttf
           - asset: fonts/Montserrat-Black.ttf
           - asset: fonts/Montserrat-ExtraLight.ttf
           - asset: fonts/Montserrat-Light.ttf
           - asset: fonts/Montserrat-Thin.ttf
           - asset: fonts/Montserrat-SemiBold.ttf
      - family: Gilroy
        fonts:
           - asset: fonts/Gilroy-Light.otf
           - asset: fonts/Gilroy-ExtraBold.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
